language: python
sudo: false
matrix:
  include:
  - python: '3.5'
    env: DEPS="numpy scipy nose cython"
  - python: '3.4'
    env: DEPS="numpy scipy nose cython"
  - python: '3.3'
    env: DEPS="numpy scipy nose cython"
  - python: '2.7'
    env: DEPS="numpy scipy nose cython"
install:
- wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh
  -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda${TRAVIS_PYTHON_VERSION:0:1}/bin:$PATH
- conda update --yes --no-deps conda
- conda config --set always_yes yes --set changeps1 no
- conda update --yes conda
- conda install --yes -c conda conda-env
- conda install --yes $DEPS pip python=${TRAVIS_PYTHON_VERSION}
- pip install coveralls
- python setup.py install
script:
- nosetests -vv --with-coverage --cover-package=abel abel/tests
deploy:
  provider: pypi
  user: DanHickstein
  password:
    secure: jhTUjFvm0I+lk9ZiOZgEx1cAvh3egHPvDF+5SSv1BcbtK6nR8MpPG6W+5JP7nVy4CCDw2x7h+M4/9A/4nrfJRO2JrUZ0Q48MwDA/vdkkZPWDwHZuGHI05rfVGE+aXKTSesryLQWv73gwPjN7Shjwa3/i2oRZQmzq7K7mHq5r5cvh+v2JWFx7D2PWNLk/mVd2dOB4BscQMnUrrK7U5JlihUc/+LtkITV84cYmwFhh3dN8R+Buu5B/GMB1vxVDWEDhbKybcPWes+DVDt9kWlyxA2vqXJg8mdsP6W8CkNqtmtfI5j8lDRJ+eF+kWQnCerGOB17sogsC29HS1Qu/H1Qdr7Jv3rSA+tQJL58nkpwFLejmYSakJLntsoeSB5H9F9P74cilaYYygtFTuUiFwTBdAHB9eY83qnAmcqpQxoKmGEC6PHlcVa9/5/IxtLRcgPGKRXY6pWACY8ytS2cSN1OU4YLPNrz8BNYhmb1j5kuFIDVZoBLPDldxTPsNvN1BSzkMEOYZFk+oenYUDJzDAkuf0sRBmknc0FjZ/GE2G73ORssbB68VGApnx4azrqlsZR83bnu3dn9cio61BPuvcg86GRGLXHCOZnECtqkkroBY1Ju2+kJ7LlXd3HyiOBpjcHbIYXr7d09i7Q+xa5IEKsHoRLL0Mqb2Nww1UnXGTA53jpw=
  on:
    tags: true
    distributions: sdist bdist_wheel
  skip_cleanup: true
